### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character in path at index 29: /svr/basex/etc/w3-catalog.xml #v10

### ISSUE THREAD

**Issue by apb2006** [Quodatum/basex-docker#8]
Unexpected error: Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 10.3
Java: Eclipse Adoptium, 17.0.5
OS: Linux, arm
Stack Trace: 
```
java.lang.IllegalArgumentException: Illegal character in path at index 29: /svr/basex/etc/w3-catalog.xml #v10
	at java.base/java.net.URI.create(Unknown Source)
	at java.base/java.net.URI.resolve(Unknown Source)
	at org.xmlresolver.CatalogManager.catalogs(CatalogManager.java:88)
	at org.xmlresolver.catalog.query.QueryCatalog.search(QueryCatalog.java:20)
	at org.xmlresolver.CatalogManager.lookupNamespaceURI(CatalogManager.java:149)
	at org.xmlresolver.CatalogManager.lookupURI(CatalogManager.java:133)
	at org.xmlresolver.CatalogResolver.resolveURI(CatalogResolver.java:103)
	at org.xmlresolver.Resolver.resolve(Resolver.java:107)
	at org.basex.query.StaticContext.resolve(StaticContext.java:156)
	at org.basex.query.QueryParser.module(QueryParser.java:785)
	at org.basex.query.QueryParser.importModule(QueryParser.java:771)
	at org.basex.query.QueryParser.importModules(QueryParser.java:753)
	at org.basex.query.QueryParser.parseLibrary(QueryParser.java:205)
	at org.basex.query.QueryContext.lambda$1(QueryContext.java:236)
	at org.basex.query.QueryContext.run(QueryContext.java:763)
	at org.basex.query.QueryContext.parseLibrary(QueryContext.java:234)
	at org.basex.query.QueryContext.parse(QueryContext.java:178)
	at org.basex.http.web.WebModule.qc(WebModule.java:100)
	at org.basex.http.web.WebModule.parse(WebModule.java:57)
	at org.basex.http.web.WebModules.parse(WebModules.java:376)
	at org.basex.http.web.WebModules.parse(WebModules.java:367)
	at org.basex.http.web.WebModules.parse(WebModules.java:367)
	at org.basex.http.web.WebModules.cache(WebModules.java:336)
	at org.basex.http.web.WebModules.find(WebModules.java:149)
	at org.basex.http.web.WebModules.restxq(WebModules.java:116)
	at org.basex.http.restxq.RestXqServlet.run(RestXqServlet.java:44)
	at org.basex.http.BaseXServlet.service(BaseXServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by apb2006** [comment]
https://github.com/Quodatum/basex-docker/commit/d9cb9c3d306789d97b093b4f20408f5dac10f6e8
